# Generated by Django 2.2.19 on 2022-08-18 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220816_1748'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='is_in_shooping_cart',
            new_name='is_in_shopping_cart',
        ),
    ]
